
# Numpy
#### This notebook contains 
1. Basic array operations (addition, subtraction, multiplication, division...)
2. Reshape
3. Flatten
4. Random
5. Unique

In [1]:
import numpy as np

### Addition

In [2]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = np.array([12, 18, 66, 92, 100])
arr3 = arr1 + arr2
print(arr3)

[ 27  43  81 127 150]


In [3]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = arr1 + 25
print(arr2)

[40 50 40 60 75]


In [4]:
arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = np.array([[21,5,9], [6,17,61]])
arr3 = arr1 + arr2
print(arr3)

[[32 37 12]
 [20 25 93]]


### Subtraction

In [5]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = np.array([12, 18, 66, 92, 100])
arr3 = arr1 - arr2
print(arr3)

[  3   7 -51 -57 -50]


In [6]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = arr1 - 15
print(arr2)

[ 0 10  0 20 35]


In [7]:
arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = np.array([[21,5,9], [6,17,61]])
arr3 = arr1 - arr2
print(arr3)

[[-10  27  -6]
 [  8  -9 -29]]


### Multiplication

In [8]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = np.array([12, 18, 66, 92, 100])
arr3 = arr2 * arr1
print(arr3)

[ 180  450  990 3220 5000]


In [9]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = arr1 * 10
print(arr2)

[150 250 150 350 500]


In [10]:
arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = np.array([[21,5,9], [6,17,61]])
arr3 = arr1 * arr2
print(arr3)

[[ 231  160   27]
 [  84  136 1952]]


### Division

In [11]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = np.array([12, 18, 66, 92, 100])
arr3 = arr1 / arr2
print(arr3)

[1.25       1.38888889 0.22727273 0.38043478 0.5       ]


In [12]:
arr1 = np.array([15, 25, 15, 35, 50])
arr2 = arr1 / 5
print(arr2)

[ 3.  5.  3.  7. 10.]


In [13]:
arr1 = np.array([[11,30,3], [14,8,32]])
arr2 = np.array([[22,5,9], [6,16,4]])
arr3 = arr1 / arr2
print(arr3)

[[0.5        6.         0.33333333]
 [2.33333333 0.5        8.        ]]


### Exponential

In [14]:
# To get exponential value use **

arr1 = np.array([5, 6, 8, 3, 9])
arr2 = np.array([2, 2, 3, 3, 2])
arr3 = arr1 ** arr2
print(arr3)

[ 25  36 512  27  81]


In [15]:
# To get exponential value use **

arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = np.array([[2,2,3], [1,3,2]])
arr3 = arr1 ** arr2
print(arr3)

[[ 121 1024   27]
 [  14  512 1024]]


In [16]:
# To get exponential value use **

arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = arr1 ** 2
print(arr2)

[[ 121 1024    9]
 [ 196   64 1024]]


### Modulus operator

In [17]:
arr1 = np.array([5, 6, 8, 3, 9])
arr2 = np.array([2, 2, 3, 3, 2])
arr3 = arr1 % arr2
print(arr3)

[1 0 2 0 1]


In [18]:
arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = np.array([[2,2,3], [1,3,2]])
arr3 = arr1 % arr2
print(arr3)

[[1 0 0]
 [0 2 0]]


In [19]:
arr1 = np.array([[11,32,3], [14,8,32]])
arr2 = arr1 % 2
print(arr2)

[[1 0 1]
 [0 0 0]]


### Dot product

In [20]:
# To get a dot product use @

arr1 = np.array([5, 6, 8, 3, 9])
arr2 = np.array([2, 2, 3, 3, 2])
arr3 = arr1 @ arr2
print(arr3)

73


In [21]:
# To get a dot product use @

arr1 = np.array([[11,32,3], [14,8,32], [1,2,3]])
arr2 = np.array([[2,2,3], [1,3,2], [4,6,2]])
arr3 = arr1 @ arr2
print(arr3)

[[ 66 136 103]
 [164 244 122]
 [ 16  26  13]]


## Reshape

In [22]:
# Change the shape of an array

arr1 = np.arange(5,9)
print(arr1)

# Create a 2x2 dim array from 1D array
arr2 = arr1.reshape(2,2)
print(arr2)

[5 6 7 8]
[[5 6]
 [7 8]]


In [23]:
# Change the shape of an array
arr1 = np.arange(9)
print(arr1)

# Create a 3x3 dim array from 1D array
arr2 = arr1.reshape(3,3)
print(arr2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# Change the shape of an array
arr1 = np.arange(18)
print(arr1)

# Create a 3x2x3 dim array from 1D array
arr2 = arr1.reshape(3,2,3)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [25]:
# Change the shape of an array
arr1 = np.arange(8)
print(arr1)

# Create a 2x2x2 dim array from 1D array
arr2 = arr1.reshape(2,2,2)
print(arr2)

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## Flatten

In [26]:
# Flatten a multi dim to a single dim

arr1 = np.array([[11,32,3], [14,8,32]])
print(arr1)
print()
arr2 = arr1.flatten()
print(arr2)

[[11 32  3]
 [14  8 32]]

[11 32  3 14  8 32]


In [27]:
# Flatten a multi dim to a single dim

arr1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr1)
print()
arr2 = arr1.flatten()
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]

[ 1  2  3  4  5  6 11 12 13 14 15 16 21 22 23 24 25 26]


### Random

In [28]:
# Generate a random integer between 0 and 100

random1 = np.random.randint(100)
print(random1)

random2 = np.random.randint(100)
print(random2)

84
81


In [29]:
# Generate a random integer between 40 and 50

random1 = np.random.randint(40, 50)
print(random1)

42


In [30]:
# Generate array of 5 random integer between 40 and 80

random1 = np.random.randint(40, 80, 5)
print(random1)

[77 57 61 55 52]


In [31]:
# Generate a 2x2 random array, with elements between 40 and 80

random1 = np.random.randint(40, 80, (2,2))
print(random1)

[[72 71]
 [66 46]]


In [32]:
# Generate a 3x3 random array, with elements between 0 and 10

random1 = np.random.randint(0, 10, (3,3))
print(random1)

[[3 8 1]
 [2 1 9]
 [2 3 8]]


In [33]:
# Generate a random float

random1 = np.random.rand(1)
print(random1)

[0.51593095]


In [34]:
# Generate array of 3 random float elements

random1 = np.random.rand(3)
print(random1)

[0.42950037 0.18256834 0.58884949]


In [35]:
# Generate 3x3 array of random float elements

random1 = np.random.rand(3,3)
print(random1)

[[0.32829987 0.11416224 0.67094006]
 [0.201388   0.76845589 0.26603474]
 [0.1253359  0.82695193 0.31011882]]


In [36]:
# Generate a random normal distribution 
# Gaussian Distribution

random1 = np.random.normal()
print(random1)

-0.1275542960574231


In [37]:
# Generate 3x3 array of random normal distribution float elements
# Gaussian Distribution

random1 = np.random.normal(size=(3,3))
print(random1)

[[-1.35871862  0.04590987 -0.77959497]
 [-0.39050767  1.80304972  0.56657468]
 [-0.56853046  1.00032129  0.7522336 ]]


In [38]:
# Generate 3x3 array of random normal distribution 
# With mean at 5 and standard deviation of 8
# loc = mean, scale = standard deviation

random1 = np.random.normal(loc=5, scale=8, size=(3,3))
print(random1)

[[-10.23752959   0.64850037   3.66477671]
 [ 17.83707909   0.47426405  12.21597471]
 [  1.86011609   9.45358143   1.70960635]]


In [39]:
# To shuffle an array use shuffle method
# Orginal array will have effect.

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
np.random.shuffle(arr1)
print(arr1)

[10 20 30 40 50]
[30 10 40 20 50]


In [40]:
# To generate a rearraged array out of an array use permutation method.
# Orginal array will have no effect.

arr1 = np.array([50, 30, 20, 40, 10])
print(arr1)
arr2 = np.random.permutation(arr1)
print(arr2)

[50 30 20 40 10]
[30 50 20 40 10]


In [41]:
# To select a random variable from an array use choice method

arr1 = [4,1,8,5,3,9,2]
elem = np.random.choice(arr1)
print(elem)

1


In [42]:
# To select a random variable from an array use choice method

arr1 = [4,1,8,5,3,9,20]
elem = np.random.choice(arr1, size=(2,2))
print(elem)

[[4 8]
 [5 9]]


## Unique

In [43]:
# Remove duplicates from the array.

arr1 = [9,4,1,8,5,4,8,3,9,20,1,4,20]
uniq = np.unique(arr1)
print(uniq)

[ 1  3  4  5  8  9 20]


In [44]:
arr1 = np.array([[1, 4, 1], [0, 3, 1], [0, 1, 5]])
arr2 = np.unique(arr1, axis=0)
print(arr2)

[[0 1 5]
 [0 3 1]
 [1 4 1]]


In [45]:
arr1 = np.array([[1, 4, 1], [0, 3, 1], [0, 1, 5]])
arr2 = np.unique(arr1, axis=1)
print(arr2)

[[1 1 4]
 [0 1 3]
 [0 5 1]]


In [46]:
arr1 = np.array([[1, 4, 1], [0, 3, 1], [0, 1, 5]])
arr2 = np.unique(arr1)
print(arr2)

[0 1 3 4 5]


In [47]:
# If return_counts is set to True, along with the unique elements
# also return the number of times each unique item appears in the array

arr1 = np.array([[1, 4, 1], [0, 3, 1], [0, 1, 5]])
arr2, unique_counts = np.unique(arr1, return_counts=True)
print(arr2, unique_counts)

[0 1 3 4 5] [2 4 1 1 1]


In [48]:
# If return_index is set to True, along with the unique elements
#  also return the indices of array that result in the unique array.

arr1 = np.array([1, 4, 1, 0, 3, 1, 0, 1, 5])
arr2, unique_index = np.unique(arr1, return_index=True)
print(arr2, unique_index)

[0 1 3 4 5] [3 0 4 1 8]
