In [1]:
import numpy as np

In [2]:
# Move axis numpy.moveaxis(a, source, destination)
# Move axes of an array to new positions. Other axes remain in their original order

myArr = [[1,2,3],[4,5,6]]
myNpArr = np.array(myArr)
print("Types",type(myArr), type(myNpArr))
print("Array",myNpArr)

myNewArr = np.moveaxis(myNpArr,0,-1)
print("Array",myNewArr)

Types <class 'list'> <class 'numpy.ndarray'>
Array [[1 2 3]
 [4 5 6]]
Array [[1 4]
 [2 5]
 [3 6]]


In [3]:
# Roll element along an axis
# numpy.roll(a, shift, axis=None)
# Roll array elements along a given axis.Elements that roll beyond the last position are re-introduced at the first.

myArr = [1,2,3,4,5,6]
myNpArr = np.array(myArr)
print("Array",myNpArr)

myNewArr = np.roll(myNpArr,0)
print("Array",myNewArr)

myNewArr = np.roll(myNpArr,1)
print("Array",myNewArr)

myNewArr = np.roll(myNpArr,2)
print("Array",myNewArr)

myNewArr = np.roll(myNpArr,3)
print("Array",myNewArr)

Array [1 2 3 4 5 6]
Array [1 2 3 4 5 6]
Array [6 1 2 3 4 5]
Array [5 6 1 2 3 4]
Array [4 5 6 1 2 3]


In [4]:
# Append
# numpy.append(arr, values, axis=None)
# Append values to the end of an array.
# Returns a copy of arr with values appended to axis, append does not occur in-place.

myArr = [1,2,3,4,5,6]
myNpArr = np.array(myArr)

print("Array",myNpArr)
myNewArr = np.append(myNpArr, 0)
print("Appended Array",myNewArr)
print("Array",myNpArr)
print("------------------------")
myNewArr = np.append(myNpArr, 3)
print("Appended Array",myNewArr)
print("Array",myNpArr)
print("------------------------")
print("Appended Array",myNewArr)
myNewArr = np.append(myNewArr, 9)
print("Appended Array",myNewArr)

Array [1 2 3 4 5 6]
Appended Array [1 2 3 4 5 6 0]
Array [1 2 3 4 5 6]
------------------------
Appended Array [1 2 3 4 5 6 3]
Array [1 2 3 4 5 6]
------------------------
Appended Array [1 2 3 4 5 6 3]
Appended Array [1 2 3 4 5 6 3 9]


In [5]:
myArr = [[1,2,3], [4,5,6], [7,8,9]]
print(myArr)
print(np.append(myArr, 0))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1 2 3 4 5 6 7 8 9 0]


# Statistics

## 1. Median

In [6]:
# Median 
# numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
# Compute the median along the specified axis. Returns the median of the array elements.

myArr = [[1,2,3], [4,5,6], [7,8,9]]
print(np.median(myArr))

print("When axis is set to zero, median of column is calculated.")
print(np.median(myArr,axis=0))

print("When axis is set to one, median of row is calculated.")
print(np.median(myArr,axis=1))


myArr = [[21,0,11, 15], [23,45,55,61], [99,36,60, 100]]
print(np.median(myArr))

print("When axis is set to zero, median of column is calculated.")
print(np.median(myArr,axis=0))

# When the number of element is even then the median is found out after the elements are sorted, 
# then the two middle numbers are added and divided by two. 
# For example in the below array when axis 1 is consided for median, the elements are sorted as
# each row contains for elements so the rows will be [0, 11, 15, 21] [23, 45, 55, 61] and [36, 60, 99, 100]
# the output will be (11+15)/2 = 13, (45+55)/2 = 50 and (60+99)/2 = 79.5 

print("When axis is set to one, median of row is calculated.")
print(np.median(myArr,axis=1))

5.0
When axis is set to zero, median of column is calculated.
[4. 5. 6.]
When axis is set to one, median of row is calculated.
[2. 5. 8.]
40.5
When axis is set to zero, median of column is calculated.
[23. 36. 55. 61.]
When axis is set to one, median of row is calculated.
[13.  50.  79.5]


In [7]:
# Finding Median ignoring NaN values 
# numpy.nanmedian(a, axis=None, out=None, overwrite_input=False, keepdims=<no value>)

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("Median",np.median(myArr))

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("NaN Median",np.nanmedian(myArr))

Median nan
NaN Median 6.0


## 2. Mean

In [8]:
# Mean
# numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
# Compute the arithmetic mean along the specified axis. Returns the average of the array elements. 
# The average is taken over the flattened array by default, otherwise over the specified axis.

myArr = [[1,2,3], [4,5,6], [7,8,9]]
print(np.mean(myArr))

myArr = [[12, 0, 45, 9], [23, 15, 55, 61], [99, 36, 21, 56]]
print(np.mean(myArr))

print(np.mean(myArr, axis=0))

print(np.mean(myArr, axis=1))

5.0
36.0
[44.66666667 17.         40.33333333 42.        ]
[16.5 38.5 53. ]


In [9]:
# Finding mean by ignoring the nan values
# numpy.nanmean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("Mean",np.mean(myArr))

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("NaN Mean",np.nanmean(myArr))

Mean nan
NaN Mean 5.428571428571429


## 3. Standard deviation

In [10]:
# Standard deviation
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the standard deviation along the specified axis.Returns the standard deviation, 
# a measure of the spread of a distribution, of the array elements. 
# The standard deviation is computed for the flattened array by default, otherwise over the specified axis.

myArr = [[1,2,3], [4,5,6], [7,8,9]]
print(np.std(myArr))

myArr = [[12, 0, 45, 9], [23, 15, 55, 61], [99, 36, 21, 56]]
print(np.std(myArr))

print(np.std(myArr, axis=0))

print(np.std(myArr, axis=1))

2.581988897471611
27.190684679377483
[38.68103181 14.76482306 14.26728971 23.42363479]
[17.03672504 19.81792118 29.31723043]


In [11]:
# Finding standard deviation by ignoring the nan values
# numpy.nanstd(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("Standard Deviation",np.std(myArr))

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("NaN Standard Deviation",np.nanstd(myArr))

Standard Deviation nan
NaN Standard Deviation 2.6649654437396615


## 4. Variance

In [12]:
# Variance 
# numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the variance along the specified axis.Returns the variance of the array elements, 
# a measure of the spread of a distribution. The variance is computed for the flattened array by default, 
# otherwise over the specified axis.

myArr = [[1,2,3], [4,5,6], [7,8,9]]
print(np.var(myArr))

myArr = [[12, 0, 45, 9], [23, 15, 55, 61], [99, 36, 21, 56]]
print(np.var(myArr))

print(np.var(myArr, axis=0))

print(np.var(myArr, axis=1))

6.666666666666667
739.3333333333334
[1496.22222222  218.          203.55555556  548.66666667]
[290.25 392.75 859.5 ]


In [13]:
# Finding variance by ignoring the nan values
# numpy.nanvar(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("Variance",np.var(myArr))

myArr = [[1, np.NaN,3], [4,np.NaN,6], [7,8,9]]
print("NaN Variance",np.nanvar(myArr))

Variance nan
NaN Variance 7.1020408163265305
